services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: drizzle
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kuroji
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/daffineq/kuroji-api
    container_name: kuroji-api
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://:@redis:6379
      - DATABASE_URL=postgresql://drizzle:postgres@postgres:5432/kuroji
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    depends_on:
      - postgres
      - redis
    command: >
      sh -c "
        echo 'Waiting for Postgres...';
        until nc -z postgres 5432; do sleep 1; done;
        echo 'Postgres ready!';
        echo 'Waiting for Redis...';
        until nc -z redis 6379; do sleep 1; done;
        echo 'Redis ready!';
        bun db:migrate;
        bun run prod
      "

volumes:
  postgres_data:
